# Generated by Django 5.2 on 2025-04-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_Category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_Image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_Quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
