# Generated by Django 5.2 on 2025-04-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productPage', '0002_product_product_category_product_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_Image',
            field=models.ImageField(blank=True, null=True, upload_to='homePage/static/images'),
        ),
    ]
