# Generated by Django 5.2 on 2025-04-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productPage', '0003_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
